version: '3.8'

# this file is used for both api integration tests (with db) and Cypress e2e tests

services:
  npb-app-test:
    # image name, set it everywhere
    image: npb-app-test
    container_name: npb-app-test
    build:
      context: .
      dockerfile: Dockerfile.test
    # container:app-process
    ports:
      - '3001:3001'
    command: yarn docker:test:start
    volumes:
      # must see src changes, frontend build prod
      - ./:/app
      - npb-test-node_modules:/app/node_modules
      - npb-test-next:/app/.next
      - npb-test-dist:/app/dist
    env_file:
      - .env.test.docker
      - .env.test.docker.local
    depends_on:
      - npb-db-test
    networks:
      - internal-test

  npb-db-test:
    image: postgres:14-alpine
    container_name: npb-db-test
    restart: unless-stopped
    # change internal port
    command: postgres -p 5435
    # expose it to host
    ports:
      - '5435:5435'
    volumes:
      - ./prisma/pg-data-test:/var/lib/postgresql/data
    # only: POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    env_file:
      - .env.test.docker.local
    networks:
      - internal-test
      - external-host

  npb-e2e:
    image: npb-e2e
    container_name: npb-e2e
    build:
      # must be in root to include prisma
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - npb-app-test
    # environment:
    #   - DEBUG=cypress:*
    env_file:
      - .env.test.docker
      - .env.test.docker.local
    # /app/package.json
    command: yarn test
    # command: bash -c 'cd /app/tests-e2e && npx wait-on http://npb-app-test:3001 && npx cypress run'
    # command: sleep infinity
    # only tests can be edited without rebuilding
    # imports from next.js app are copied in Dockerfile
    # app is prod built anyway
    volumes:
      - ./tests-e2e/cypress:/app/tests-e2e/cypress
      - ./tests-e2e/cypress.json:/app/tests-e2e/cypress.json
    networks:
      - internal-test

volumes:
  npb-test-node_modules:
  npb-test-next:
  npb-test-dist:

networks:
  internal-test:
    external: false
  # for adminer dev d-c
  external-host:
    external: true
